### ISSUE TITLE
[Bug] OptimizedInventories true, hoppers cannot push item into dropper

### ISSUE THREAD

**Issue by aria1th** [2No2Name/hopperOptimizations#13] opened 2020-06-07 14:26 UTC
![2020-06-07_23 03 10](https://user-images.githubusercontent.com/35677394/83971444-331af200-a916-11ea-98bc-a56e5d910f80.png)
![2020-06-07_23 03 08](https://user-images.githubusercontent.com/35677394/83971450-34e4b580-a916-11ea-9f32-596d52224acf.png)

hopper is directly facing into dropper but it does not pushes item into it. Hopper is not powered by anything.

**Comment by 2No2Name** [comment] 2020-06-07 18:16
Which version are you using? The latest version does not have a rule with that name anymore, as it does not make sense to install the mod with the rule turned off. If you are not using the latest version, please update to the latest release https://github.com/2No2Name/hopperOptimizations/releases.
I cannot reproduce your issue. In a past version there were compatibility issues with other mods that are modifying the dropper. If you are using the latest version please give me more detailed instructions on how to reproduce this

**Comment by 2No2Name** [comment] 2020-06-07 18:36
Which version are you using? If you are not using the latest version, please update to the latest release https://github.com/2No2Name/hopperOptimizations/releases.

**Comment by aria1th** [comment] 2020-06-08 10:06
I'm using the latest version. I found all options are true, not only optimizedinventories. It happens when hopper have consistent flow of in & out, when it tries to push item into dropper.

**Comment by 2No2Name** [comment] 2020-06-08 12:39
I cannot reproduce this by trying around. Can you provide a world download, schematic or structure block file, so I can debug using the setup you have?

**Comment by aria1th** [comment] 2020-06-08 13:03
[corruptcheck.zip](https://github.com/2No2Name/hopperOptimizations/files/4746015/corruptcheck.zip)

It's ilmango's fast acacia farm-based, with shulker loader. I placed spruce tree by 36tick interval, and afked for 4 hours, and by some point hopper failed to push items into dropper. I don't know it is the cause of the server crash, but server crashed due to [23:05:13] [Server Watchdog/FATAL]: A single server tick took 60.00 seconds (should be max 0.05), After the crash, server admin has disabled the mod, and hopper worked as it should be.

**Comment by aria1th** [comment] 2020-06-08 13:22
I actually found that not only the tree farm, but also some kind of droppers repeatedly getting triggered and getting flows horizontally from dropper would make problem. All dropper/hopper did not had chunk border problem, and it's built on spawn chunk, always loaded by carpet fake player.

Mods used : fabric -Carpet 1.3.23, Carpet extra 1.3.18, Lithium, Phosphorus, Servux, hopperOptimizations ; MC java version 1.15.2

**Comment by aria1th** [comment] 2020-06-08 13:40
I've successed reproducing this bug, with OptimizedEntityHopperInteraction true + OptimizedInventories true + OptimizedItemStackEmptyCheck true.
It is world file. 

![2020-06-08_22 37 37](https://user-images.githubusercontent.com/35677394/84036997-f106b480-a9d8-11ea-8f2e-9cc527ea8c19.png)

Middle hopper-dropper line is bugged, hopper is full of bonemeal but does not send any of it to dropper.


[corruptcheck (1).zip](https://github.com/2No2Name/hopperOptimizations/files/4746268/corruptcheck.1.zip)

**Comment by 2No2Name** [comment] 2020-06-08 15:47
I still can't reproduce it, ran the farm for half an hour, and did not see any problems besides the shulker box unloader being too slow for the farm

**Comment by aria1th** [comment] 2020-06-08 16:23
I thought that dropper was 'stable' blocked... maybe using tick warp command, I reproduced it with tick rate 300

Reloading the map/server actually solves the problem, but it still occurs.  Actually shulker unloader is intended to be slow, farm runs less than 1/3 speed (36tick). I refilled bonemeal and summoned fake player, and set rate 300 and it occured again

**Comment by aria1th** [comment] 2020-06-08 16:52
![2020-06-08_22 35 30](https://user-images.githubusercontent.com/35677394/84058047-9cbcfe00-a9f3-11ea-891e-8b03f99c0ac9.png)
![2020-06-08_22 35 16](https://user-images.githubusercontent.com/35677394/84058051-9dee2b00-a9f3-11ea-9838-ecbfae430b2b.png)
![2020-06-08_22 35 29](https://user-images.githubusercontent.com/35677394/84058053-9e86c180-a9f3-11ea-82ac-3254b0ab15df.png)

Reloading world / restarting server solves the problem, but I don't know what's happening.

**Comment by aria1th** [comment] 2020-06-08 17:24
Found that just having chest-hopper-dropper/dispenser with constant flow can jump into problem randomly, with very long period of time... I guess it's cache related problem. Not only in my computer, public server(fabric +carpet mod) had the problem. It is solved when server restarts, which means it do not save blocked state.

**Comment by 2No2Name** [comment] 2020-06-08 20:07
I made this contraption with an upwards facing dropper and the observer clock. I am tickwarping it and I am not encountering the problem. Do you have a minimal setup that reliably gets into the broken state after some time?
![2020-06-08_21 51 42](https://user-images.githubusercontent.com/50278648/84075244-193fe480-a9d4-11ea-8331-bc21fb741ef1.png)

**Comment by aria1th** [comment] 2020-06-09 01:02
[general_craft.zip](https://github.com/2No2Name/hopperOptimizations/files/4749363/general_craft.zip)
I added tons of hoppers connected and used autocrafting module, and tick warped for a long time. I'd add schematic soon. I don't think it is reliable but seems like time does matters

**Comment by 2No2Name** [comment] 2020-09-17 13:02
There were many changes in the latest version, I believe this should be fixed now. Can you test it again, please?

**Comment by aria1th** [comment] 2020-09-18 06:02
seems okay, Not found any stopped hopper

**Comment by 2No2Name** [comment] 2020-09-21 12:35
Thank you. If it occurs again, just create a new issue

**Closed as completed by 2No2Name** 2020-09-21 12:35 UTC
Labels: bug, info needed
